apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - name: rest
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: internal
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch