apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend-ingress
  namespace: krakend
spec:
  rules:
    - host: krakend.reshout.com
      http:
        paths:
          - backend:
              service:
                name: krakend-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
